const commentData = [
  "In a new column for the Financial Times, I offer the president some advice: Charlie Cook has even drafted the speech:",
  "Assuming Johnson makes the same amount per year as his predecessor, which would be $8.75 million/year, the head of McDonald's would have to work 1,060,606 hours as a line cook to maintain his salary.",
  "Tom helped cook lunch.",
  "Helen Hunt is kind and pleasant in The Sessions, but her seriously wobbly Bahstin accent disqualifies her immediately.",
  "Any restaurant worth its pink Himalayan salt is selling it.",
  "It is a super gentle way to cook the pheasant, and it's foolproof—if you leave the meat in too long, the stock's temperature is going down anyway, so it's very forgiving.",
  "A popular variant for those folks praises a local sweet, Rowntree’s Fruit Gums and Pastilles: ‘Rowntree’s of York Gave Best In Value.’” Throughout Roy G.",
  "Sweet Dreams Unfortunately, we're talking about the mid-tempo single here, which is just okay.",
  "Add the chicken broth, bring back to a simmer, cover, and cook an additional 15 minutes until the vegetables are soft.",
  "Burger and Public Safety personnel should be held accountable for these acts through appropriate disciplinary channels.",
  "It goes without saying that hunger is the best sauce.",
  "In the town of Espanola in northern New Mexico, for example, there are places where you can find chicos—oven-dried sweet corn kernels—on the menu.",
  "“All those people who used to want to beat the hell out of me because of my long hair—now their hair was long!” In the mid-1970s, when Lynyrd Skynyrd sang “Sweet Home Alabama” at the Oakland Coliseum",
  "This tea is really sweet.",
  "The schoolhouse was burnt to ashes.",
  "Sustainable nourishment comes from knowing how to cook, tending the land, appreciating our rich food traditions, and taking care of each other.",
  "Then, in the final trial, participants tasted similar sweet treats that came with either a pleasant note (I picked this just for you.",
  "This is food science. Flavor is mostly aroma, and aromatic compounds are volatile.",
  "In August, it retired The King, and announced its revamped marketing approach would be more food-centric. It's first order of business: a new burger.  >",
  "Fresh and grassy, with a smaller spicy kick then years gone past but still a kick that tickles the back of your throat and almost makes you cough.",
  "As soon as I'm back in Shanghai, I'll cook up a delicious meal of rice noodles with crab.",
  "It turns out that the stronger the garlic, the greater the voltage generated.",
  "A continental recession is bad enough, but it is not the same as dissolution and chaos After a pleasant lull over the past six months, panic over the fate of Europe has flared once again.",
  "Before Martelly became head of state five years ago, he was a pop star known as “Sweet Micky.” Micky was famous for saying or doing anything to get a rise out of a crowd.",
  "Salt is necessary for cooking.",
  "This cake tastes too sweet for me.",
  "Forgive them for doing that grilled chicken silliness, because their original recipe with a side of potato wedges is salty goodness at its finest.  Long John Silver's: I had a fried shrimp here and hushpuppies here once.",
  "Tom ordered large fries.",
  "(Seth Meyers is back as Boston Powers, Charlie Day spoofs Dane Cook, and Adam Levine is attacked by a Hawk.) : Live from Cee Lo Green's basement: Cee Lo Green—together with dinosaur-suit clad Mr.",
  "Vinsanto, the fruity, naturally sweet wine produced from grapes partly dried in the island sun, complements any dessert—the traditional honey stuffed cookies, or a simple plate of late-summer fruits.",
  "Telling the world that the cook needs to start a garden and shop at Whole Foods would be like a music critic deciding a song can't be good if it has no redeeming social value.",
  "Some other treaties of the Cold War era, notably the ABM treaty and the Salt I and Salt II treaties of the 1970s, now seem enmeshed in the arcana of that era (though I remember taking part in heated debates on all of them).",
  "Great recipe, it was super easy to make",
  "I wasn't super impressed with the end product, but food is food lol",
  "Thank you so much for another great recipe! I can't wait to see what you make next!",
  "Garlic really isn't that good in this dish. Leave it out next time.",
  "This recipe is really overrated in my opinion",
  "This recipe is really underrated in my opintion",
  "This tastes just like Chipotle!",
  "This tasted really inauthentic, I would recommend you try using less substitutes.",
  "Wow this is just how I used to have it back home!",
  "Hi, great recipe but I noticed it isn't full vegan. Any change you could edit this post to remove the tag? Thanks!",
  "Was really good :)",
  "Wasn't so good, I would recommend adding more salt.",
];

module.exports = commentData;
