const commentData = [
  "In a new column for the Financial Times, I offer the president some advice: Charlie Cook has even drafted the speech:",
  "If even a fraction of what is spent onscreening was invested in the intelligence services we would take areal step toward making air travel safer and more pleasant.  -- Marijn Ornstein, chief of security, Schiphol Airport, Amsterdam (via Bruce Schneier)",
  "Assuming Johnson makes the same amount per year as his predecessor, which would be $8.75 million/year, the head of McDonald's would have to work 1,060,606 hours as a line cook to maintain his salary.",
  "Tom helped cook lunch.",
  "Helen Hunt is kind and pleasant in The Sessions, but her seriously wobbly Bahstin accent disqualifies her immediately.",
  "If I had a girlfriend, she'd kill me.—Krusty Gets Kancelled (Season 4, Episode 22), when a taco he sold is returned.[there's maybe a better one, but everything that comes out of this kid's mouth works] Bingo bango, sugar in the gas tank.",
  "Any restaurant worth its pink Himalayan salt is selling it.",
  "It is a super gentle way to cook the pheasant, and it's foolproof—if you leave the meat in too long, the stock's temperature is going down anyway, so it's very forgiving.",
  "The original sellers have already been keeping a low profile, and Gawker and its pot of $200,000 weren't enough to obtain the video. Gawker editor John Cook wrote on June 4 that the owner of the video told him the crack-smoking film was gone, though an intermediary told him that a copy exists outside of Toronto.",
  "A popular variant for those folks praises a local sweet, Rowntree’s Fruit Gums and Pastilles: ‘Rowntree’s of York Gave Best In Value.’” Throughout Roy G.",
  "Sweet Dreams Unfortunately, we're talking about the mid-tempo single here, which is just okay.",
  "Add the chicken broth, bring back to a simmer, cover, and cook an additional 15 minutes until the vegetables are soft.",
  "Her shirt was stained with sauce.",
  "While 60 percent of the world’s pre-peeled garlic is bought by Americans, it’s hard to believe those same shoppers would care to purchase it if they knew its stalks were removed by Chinese prisoners’ teeth (one of the more gruesome facts revealed in the series is that the inmates’ thumbnails invariably fall off from repetitive labor).",
  "At the end of the song, the gunfighter lays dying, while Felina kneels by his side. Walt, in fact, is shot in the side by a bullet, and dies with a meth lab at his side after admitting to Skyler that being a meth cook became his true passion, his love, his Baby Blue, which is the title of the Badfinger song that plays at the episode's close. But back to El Paso, this is how its story ends:  Felina is strong and I rise where I've fallen, Though I am weary I can't stop to rest.",
  "Burger and Public Safety personnel should be held accountable for these acts through appropriate disciplinary channels.",
  "The aroma of the mugwort is also very nice. From 1989 through 1991 I was invited often to Kim Jong Il's official residence.",
  "It goes without saying that hunger is the best sauce.",
  "In the town of Espanola in northern New Mexico, for example, there are places where you can find chicos—oven-dried sweet corn kernels—on the menu.",
  "A passenger at Salt Lake City (SLC) received a pat-down after an anomaly was detected during advanced imaging technology screening. During the pat-down, officers discovered a fully loaded .22 caliber firearm inside his boot.",
  "Though Arrington didn't name names in his story, one angel investor has already admitted to attending the meeting and--in a salty blog post--calls him dead f--ing wrong. A number of other technology bloggers have raised skepticism about his story.",
  "“All those people who used to want to beat the hell out of me because of my long hair—now their hair was long!” In the mid-1970s, when Lynyrd Skynyrd sang “Sweet Home Alabama” at the Oakland Coliseum against the backdrop of a giant Confederate flag, they looked oddly similar to the hippies of Telegraph Avenue.",
  "This tea is really sweet.",
  "The schoolhouse was burnt to ashes.",
  "Sustainable nourishment comes from knowing how to cook, tending the land, appreciating our rich food traditions, and taking care of each other.",
  "Men pepper their sentences with unnecessary “likes” and “sorrys.” I haven’t read any articles encouraging them to change this behavior.",
  "Then, in the final trial, participants tasted similar sweet treats that came with either a pleasant note (I picked this just for you.",
  "This is food science. Flavor is mostly aroma, and aromatic compounds are volatile.",
  "In August, it retired The King, and announced its revamped marketing approach would be more food-centric. It's first order of business: a new burger.  >",
  "We need a national campaign to sue the crap out of these schools.  The disgusting and bigoted principals and administrators may be afraid to stand up for a gay kid, but they won't hesitate to protect themselves against a six figure damages claim.",
  "Fresh and grassy, with a smaller spicy kick then years gone past but still a kick that tickles the back of your throat and almost makes you cough.",
  "Kerr has been sued four times, three times by CMS, and in each case, the agency sought to seize a chunk of her wages at Burger King.",
  "          Black motherhood is not only relentless, I believe, it also engenders a split-screen view of the world that makes it possible for me to sit in my living room and placidly put together a cupcake jigsaw puzzle while listening to my daughter Isabella’s sweet, soothing voice as she reads to me from Little Women, and at the same time think thoughts that Marmee, the novel’s matriarch, surely never thought, such as: Whoever hurts her, I will destroy.",
  "No, it's their continued insistence on using the disgusting idiom bikini body. Move Over Kendall!",
  "As soon as I'm back in Shanghai, I'll cook up a delicious meal of rice noodles with crab.",
  "It turns out that the stronger the garlic, the greater the voltage generated.",
  "Instead, he quips that they’re “my mother, my wife, my daughter.” (The joke isn’t any funnier in Chinese.) Elsewhere, viewers suffer through laugh tracks, clownish sound effects (“boink!”), and excruciating ‘joke cues’ that spoon-feed humor to the audience.",
  "[Us Weekly] Now that Nick Jonas is a free man — the Jonas Brothers have broken up, yes, but also they arrested some drifter for that string of disappearances, so it looks like Nick got away with it (Nick Jonas has a lot in common with Adam Levine, if you catch my drift) — he has decided to buy his own sweet pad to chase around with a hammer entertain the ladies in.",
  "A continental recession is bad enough, but it is not the same as dissolution and chaos After a pleasant lull over the past six months, panic over the fate of Europe has flared once again.",
  "Before Martelly became head of state five years ago, he was a pop star known as “Sweet Micky.” Micky was famous for saying or doing anything to get a rise out of a crowd.",
  "There's surely nothing normal or healthy about buying thousands of diapers when you are childless, or sacrificing entire rooms of your house to jars of tomato sauce and enough tubes of toothpaste to last an average person 40 years.",
  "Al Jazeera reported two weeks ago that 90 families had been protesting for three weeks in New Delhi, demanding government protection: At a protest site in the heart of India's capital, New Delhi, four gang-rape victims -- the youngest of whom is 13 -- drape dupattas (scarves) across their faces as they help other women cook for the fellow protesters...",
  "Salt is necessary for cooking.",
  "This cake tastes too sweet for me.",
  "Forgive them for doing that grilled chicken silliness, because their original recipe with a side of potato wedges is salty goodness at its finest.  Long John Silver's: I had a fried shrimp here and hushpuppies here once.",
  "Tom ordered large fries.",
  "(Seth Meyers is back as Boston Powers, Charlie Day spoofs Dane Cook, and Adam Levine is attacked by a Hawk.) : Live from Cee Lo Green's basement: Cee Lo Green—together with dinosaur-suit clad Mr.",
  "Vinsanto, the fruity, naturally sweet wine produced from grapes partly dried in the island sun, complements any dessert—the traditional honey stuffed cookies, or a simple plate of late-summer fruits.",
  "Telling the world that the cook needs to start a garden and shop at Whole Foods would be like a music critic deciding a song can't be good if it has no redeeming social value.",
  "Some other treaties of the Cold War era, notably the ABM treaty and the Salt I and Salt II treaties of the 1970s, now seem enmeshed in the arcana of that era (though I remember taking part in heated debates on all of them).",
];

module.exports = commentData;
